# Generated by Django 5.1.1 on 2024-10-10 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_category_searchtag_review_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
