# Generated by Django 5.1.1 on 2024-10-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_is_active',
            new_name='is_active_reviews',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='review',
            name='director',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_updated',
        ),
        migrations.AddField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=195, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movie_app.searchtag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=195, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
